-- ================================================================
-- HỆ THỐNG TRA CỨU ĐỀ THI CHUYÊN TIN HỌC - SUPABASE SCHEMA
-- ================================================================

-- 1. Tạo bảng lưu trữ bài giải / code Python đóng góp từ học sinh
CREATE TABLE IF NOT EXISTS exam_solutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id INTEGER NOT NULL,
    exam_title TEXT NOT NULL,
    problem_name TEXT NOT NULL,
    author TEXT NOT NULL,
    language TEXT DEFAULT 'python',
    code TEXT NOT NULL,
    explanation TEXT,
    likes INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Bật Row Level Security (RLS) để kiểm soát quyền
ALTER TABLE exam_solutions ENABLE ROW LEVEL SECURITY;

-- 3. Cho phép bất kỳ ai (kể cả khách truy cập) đều có thể xem bài giải (Public Read)
CREATE POLICY "Cho phep moi nguoi doc bai giai"
ON exam_solutions FOR SELECT
USING (true);

-- 4. Cho phép học sinh gửi bài giải mới mà không cần đăng nhập (Public Insert)
CREATE POLICY "Cho phep hoc sinh gui bai giai"
ON exam_solutions FOR INSERT
WITH CHECK (
    char_length(author) >= 1 AND 
    char_length(problem_name) >= 1 AND 
    char_length(code) >= 5
);

-- 5. Tạo Index tối ưu tốc độ truy vấn theo exam_id
CREATE INDEX IF NOT EXISTS idx_exam_solutions_exam_id ON exam_solutions (exam_id);
